apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: p5z6nio8w-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/p5z6nio8w-java-quarkus-gitops